# https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md
# https://docs.docker.com/compose/intro/history/
version: "3.8"

services:
  # https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md#service-configuration-reference

  otel-collector:
    # https://hub.docker.com/r/otel/opentelemetry-collector-contrib
    # https://opentelemetry.io/docs/collector/installation/#docker-compose
    image: otel/opentelemetry-collector-contrib:0.116.1

    deploy:
      mode: replicated
      replicas: 1

    user: "1000"

    environment:
      # https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md#environment
      TZ: "Asia/Seoul"

    networks:
      monitoring-network:
      # service-network:

  alloy:
    # https://hub.docker.com/r/grafana/alloy
    # https://grafana.com/docs/alloy/latest/set-up/install/docker/
    image: grafana/alloy:v1.5.1

    deploy:
      mode: replicated
      replicas: 1

    user: "1000"

    environment:
      # https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md#environment
      TZ: "Asia/Seoul"

    networks:
      monitoring-network:
      service-network:
        aliases:
          - "otel-collector"

  grafana:
    # https://hub.docker.com/r/grafana/grafana-oss
    # https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
    image: grafana/grafana-oss:11.4.0

    deploy:
      mode: replicated
      replicas: 1

    user: "1000"

    environment:
      # https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md#environment
      TZ: "Asia/Seoul"

    networks:
      monitoring-network:

  tempo:
    # https://hub.docker.com/r/grafana/tempo
    # https://github.com/grafana/tempo/tree/main/example/docker-compose
    image: grafana/tempo:2.6.1

    deploy:
      mode: replicated
      replicas: 1

    user: "1000"

    environment:
      # https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md#environment
      TZ: "Asia/Seoul"

    networks:
      monitoring-network:

  loki:
    # https://hub.docker.com/r/grafana/loki
    # https://grafana.com/docs/loki/latest/setup/install/docker/
    image: grafana/loki:3.3.2

    deploy:
      mode: replicated
      replicas: 1

    user: "1000"

    environment:
      # https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md#environment
      TZ: "Asia/Seoul"

    networks:
      monitoring-network:

  cadvisor:
    # https://gcr.io/cadvisor/cadvisor
    # https://github.com/google/cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.49.1

    deploy:
      mode: replicated
      replicas: 1

    user: "1000"

    environment:
      # https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md#environment
      TZ: "Asia/Seoul"

    networks:
      monitoring-network:

  prometheus:
    # https://quay.io/repository/prometheus/prometheus
    # https://prometheus.io/docs/prometheus/latest/installation/#using-docker
    image: quay.io/prometheus/prometheus:v3.0.1

    deploy:
      mode: replicated
      replicas: 1

    user: "1000"

    environment:
      # https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md#environment
      TZ: "Asia/Seoul"

    networks:
      monitoring-network:

  node-exporter:
    # https://quay.io/repository/prometheus/node-exporter
    # https://github.com/prometheus/node_exporter
    image: quay.io/prometheus/node-exporter:v1.8.2

    deploy:
      mode: replicated
      replicas: 1

    user: "1000"

    environment:
      # https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md#environment
      TZ: "Asia/Seoul"

    networks:
      monitoring-network:

  alertmanager:
    # https://quay.io/repository/prometheus/alertmanager
    # https://prometheus.io/docs/alerting/latest/configuration/
    image: quay.io/prometheus/alertmanager:v0.27.0

    deploy:
      mode: replicated
      replicas: 1

    user: "1000"

    environment:
      # https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md#environment
      TZ: "Asia/Seoul"

    networks:
      monitoring-network:

networks:
  # https://github.com/docker/compose/blob/v1/docs/Compose%20file%20reference%20(legacy)/version-3.md#network-configuration-reference
  monitoring-network:
    name: monitoring-network
    driver: overlay
    attachable: true
  
  service-network:
    name: service-network
    driver: overlay
    attachable: true
